# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)

platform :mac do

  before_all do 
    ENV["BuildFolder"]  = "~/Desktop/ScriptDeckBuilds"
  end



  desc "Build the .app, and store it in ~/Desktop/ScriptDeckBuilds"
  lane :buildApp do
    gym(
      skip_package_pkg: true,
      output_directory: ENV["BuildFolder"]
    )
  end
end
